//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_jugglejoyEntities : DbContext
    {
        public db_jugglejoyEntities()
            : base("name=db_jugglejoyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_blogs> tbl_blogs { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_contact> tbl_contact { get; set; }
        public virtual DbSet<tbl_faq> tbl_faq { get; set; }
        public virtual DbSet<tbl_options> tbl_options { get; set; }
        public virtual DbSet<tbl_question> tbl_question { get; set; }
        public virtual DbSet<tbl_subcategory> tbl_subcategory { get; set; }
        public virtual DbSet<tbl_subscriber> tbl_subscriber { get; set; }
        public virtual DbSet<tbl_country> tbl_country { get; set; }
        public virtual DbSet<tbl_state> tbl_state { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_faq_category> tbl_faq_category { get; set; }
        public virtual DbSet<tbl_blogcategory> tbl_blogcategory { get; set; }
        public virtual DbSet<tbl_banner> tbl_banner { get; set; }
        public virtual DbSet<tbl_answer> tbl_answer { get; set; }
        public virtual DbSet<tbl_task> tbl_task { get; set; }
        public virtual DbSet<tbl_log> tbl_log { get; set; }
        public virtual DbSet<tbl_chat> tbl_chat { get; set; }
        public virtual DbSet<tbl_chatfile> tbl_chatfile { get; set; }
        public virtual DbSet<tbl_minitask> tbl_minitask { get; set; }
        public virtual DbSet<tbl_optiontype> tbl_optiontype { get; set; }
        public virtual DbSet<tbl_taskattachment> tbl_taskattachment { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_recommendations> tbl_recommendations { get; set; }
        public virtual DbSet<tbl_survey> tbl_survey { get; set; }
        public virtual DbSet<tbl_surveyQue> tbl_surveyQue { get; set; }
        public virtual DbSet<tbl_note> tbl_note { get; set; }
        public virtual DbSet<tbl_price> tbl_price { get; set; }
        public virtual DbSet<tbl_gifts> tbl_gifts { get; set; }
        public virtual DbSet<tbl_subscription> tbl_subscription { get; set; }
        public virtual DbSet<tbl_cms> tbl_cms { get; set; }
        public virtual DbSet<tbl_tempgifts> tbl_tempgifts { get; set; }
        public virtual DbSet<tbl_blogviews> tbl_blogviews { get; set; }
        public virtual DbSet<tbl_CancelAnswer> tbl_CancelAnswer { get; set; }
        public virtual DbSet<tbl_CancelCat> tbl_CancelCat { get; set; }
        public virtual DbSet<tbl_CancelReason> tbl_CancelReason { get; set; }
    }
}
