//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tempgifts
    {
        public int TempGiftID { get; set; }
        public string GiftCode { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string SenderEmail { get; set; }
        public string RecepientName { get; set; }
        public string RecepientEmail { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string Message { get; set; }
        public string SenderName { get; set; }
        public Nullable<int> Status { get; set; }
        public string MailSender { get; set; }
        public string MailReceiver { get; set; }
    }
}
