//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_answer
    {
        public int AnswerID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> MinitaskID { get; set; }
        public string OtherAnswer { get; set; }
    
        public virtual tbl_question tbl_question { get; set; }
        public virtual tbl_task tbl_task { get; set; }
    }
}
