//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_options
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_options()
        {
            this.tbl_optiontype = new HashSet<tbl_optiontype>();
        }
    
        public int OptionID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Question { get; set; }
        public string OptionType { get; set; }
        public string Placeholder { get; set; }
    
        public virtual tbl_question tbl_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_optiontype> tbl_optiontype { get; set; }
    }
}
