//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subscriber
    {
        public int SubscriberId { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> SubscribedDate { get; set; }
    }
}
