//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_taskattachment = new HashSet<tbl_taskattachment>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipPostalCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> State { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.Guid> Salt { get; set; }
        public Nullable<System.Guid> PwdResetKey { get; set; }
        public Nullable<System.DateTime> PwdKeyCreatedTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string UserType { get; set; }
        public Nullable<int> HeardFrom { get; set; }
        public string PartnerEmail { get; set; }
        public Nullable<int> HandlerID { get; set; }
        public Nullable<int> otp { get; set; }
        public string SubscriptionId { get; set; }
        public Nullable<int> SubscriptionStatus { get; set; }
    
        public virtual tbl_country tbl_country { get; set; }
        public virtual tbl_state tbl_state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_taskattachment> tbl_taskattachment { get; set; }
    }
}
