//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_recommendations
    {
        public int RecID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public string Name { get; set; }
        public string Rating { get; set; }
        public string Note { get; set; }
        public string Price { get; set; }
        public string Availability { get; set; }
        public string NextStep { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public Nullable<int> MiniTaskID { get; set; }
    
        public virtual tbl_task tbl_task { get; set; }
    }
}
