//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_survey
    {
        public int SurveyID { get; set; }
        public Nullable<int> SurveyQueID { get; set; }
        public string Rate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public Nullable<int> TaskID { get; set; }
    
        public virtual tbl_surveyQue tbl_surveyQue { get; set; }
    }
}
