//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_question()
        {
            this.tbl_options = new HashSet<tbl_options>();
            this.tbl_answer = new HashSet<tbl_answer>();
        }
    
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public string SubCategoryID { get; set; }
        public string OptionType { get; set; }
        public string Placeholder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_options> tbl_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_answer> tbl_answer { get; set; }
    }
}
