//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_taskattachment
    {
        public int TaskAttachmentID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
    
        public virtual tbl_task tbl_task { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
