//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CancelReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CancelReason()
        {
            this.tbl_CancelAnswer = new HashSet<tbl_CancelAnswer>();
        }
    
        public int CancelID { get; set; }
        public Nullable<int> CancelCatID { get; set; }
        public string Reason { get; set; }
        public string OptionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CancelAnswer> tbl_CancelAnswer { get; set; }
        public virtual tbl_CancelCat tbl_CancelCat { get; set; }
    }
}
