//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blogs
    {
        public int BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogImage { get; set; }
        public string BlogDescription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual tbl_blogcategory tbl_blogcategory { get; set; }
    }
}
