//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_note
    {
        public int NoteID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> HandlerID { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public string Note { get; set; }
        public string Filepath { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
