//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_minitask
    {
        public int MinitaskID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string UserNote { get; set; }
        public string MoreOptions { get; set; }
    
        public virtual tbl_task tbl_task { get; set; }
    }
}
