//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CancelAnswer
    {
        public int CancelAnswerID { get; set; }
        public Nullable<int> CancelID { get; set; }
        public string SpecificReaspn { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tbl_CancelReason tbl_CancelReason { get; set; }
    }
}
