//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public int AdminID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public System.Guid Salt { get; set; }
        public string EmailID { get; set; }
        public string PhoneNo { get; set; }
        public System.Guid PwdResetKey { get; set; }
        public System.DateTime PwdKeyCreatedTime { get; set; }
    }
}
