//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_task()
        {
            this.tbl_answer = new HashSet<tbl_answer>();
            this.tbl_log = new HashSet<tbl_log>();
            this.tbl_minitask = new HashSet<tbl_minitask>();
            this.tbl_taskattachment = new HashSet<tbl_taskattachment>();
            this.tbl_recommendations = new HashSet<tbl_recommendations>();
        }
    
        public int TaskID { get; set; }
        public Nullable<int> FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Description { get; set; }
        public string Fileattachment { get; set; }
        public string Urgency { get; set; }
        public string Repeating { get; set; }
        public string WorkTime { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string TaskTitle { get; set; }
        public string DeadlineType { get; set; }
        public Nullable<int> AssistantID { get; set; }
        public string UserNote { get; set; }
        public string MoreOptions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_answer> tbl_answer { get; set; }
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_subcategory tbl_subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_log> tbl_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_minitask> tbl_minitask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_taskattachment> tbl_taskattachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_recommendations> tbl_recommendations { get; set; }
    }
}
