//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subscription
    {
        public int SubscriptionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> SubscriptionFee { get; set; }
        public string TransactionNo { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionMsg { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string StripeOrderID { get; set; }
        public string StripePaymentType { get; set; }
        public string StripeReturnData { get; set; }
        public Nullable<int> GiftID { get; set; }
    }
}
