//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faq
    {
        public int FaqID { get; set; }
        public string FaqQuestion { get; set; }
        public string FaqAnswer { get; set; }
        public Nullable<int> Faq_categoryID { get; set; }
        public Nullable<int> SortPreference { get; set; }
    
        public virtual tbl_faq_category tbl_faq_category { get; set; }
    }
}
