//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chat
    {
        public int ChatID { get; set; }
        public Nullable<int> ToId { get; set; }
        public Nullable<int> FromId { get; set; }
        public string ChatText { get; set; }
        public Nullable<int> ChatreadStatus { get; set; }
        public Nullable<System.DateTime> ChatDate { get; set; }
        public string Subject { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> AssistantId { get; set; }
    }
}
