//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juggle_joy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> ToID { get; set; }
        public string Notification { get; set; }
        public string ReadStatus { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
